export const SEARCH_USERS = 'SEARCH_USERS'
export const CLEAR_USERS = 'CLEAR_USERS'
export const SINGLE_USER = 'SINGLE_USER'
export const GET_REPOS = 'GET_REPOS'
export const SET_LOADING = 'SET_LOADING'
export const GET_DATA = 'GET_DATA'